python3 -m train \
	--data_path ../data/Neurology \
	--log_path ./logs/Neu_STHG \
	--model_save_path ./Models/Neu_STHG \
	--device cuda:0 \
	--model STHG \
	--agg_type gcn \
	--backbone Sage \
	--test_type full \
	--batch_size 1024 \
	--nhead 8 \
	--num_layers 4 \
	--input_dim 300 \
	--hidden_dim 256 \
	--output_dim 1 \
	--learning_rate 5e-4 \
	--dropout_rate 0.5 \
	--epoch 20 \
	--sample_size_1 -1 \
	--sample_size_2 -1 \
	--attn_wnd 5 \
	--year_start 1950 \
	--year_end 2010 \
	--year_interval 10